blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/lwshakib/xtractify-web-scraping-extension/discussions
    about: Please use GitHub Discussions for general questions or help requests.
  - name: Security Issues
    url: https://github.com/lwshakib/xtractify-web-scraping-extension/security/advisories
    about: Please report security vulnerabilities here instead of opening a public issue.
